"""first_v1

Revision ID: 5330e3120877
Revises: 
Create Date: 2019-06-02 20:55:48.090462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5330e3120877'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='students')
    op.drop_table('students')
    op.drop_index('name', table_name='courses')
    op.drop_table('courses')
    op.drop_table('first')
    op.drop_table('Person')
    op.drop_table('tb_student_course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_student_course',
    sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='tb_student_course_ibfk_2'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='tb_student_course_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Person',
    sa.Column('Id', mysql.INTEGER(display_width=5), autoincrement=False, nullable=True),
    sa.Column('Emaile', mysql.VARCHAR(length=25), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('first',
    sa.Column('id', mysql.SMALLINT(display_width=11), autoincrement=True, nullable=False),
    sa.Column('age', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False, comment='??'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('courses',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'courses', ['name'], unique=True)
    op.create_table('students',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'students', ['name'], unique=True)
    # ### end Alembic commands ###
